### ISSUE TITLE
As a conference organizer I need the MIRRW signups to not be a backdoor into the space without a ticket.

### ISSUE THREAD

**Issue by dpcybuck** [mzbat/mirr#3]
If there are attendance restrictions on the space.
 How do we know if the people signing up for the MIRRW have tickets to the event?  Sometimes the "lobby" is open, and the workshop is in the lobby...not problem there.
But if the workshop inside the entryway to the event it could make publicizing the workshop difficult.

**Comment by YesItsKathleen** [comment]
typically if this is part of a con, you have to delineate if con attendance and ticket purchase is a requirement. We do both at our events.

**Comment by dpcybuck** [comment]
Ok, then something needs to go into the sign up forms and/or into the guidance for this workshop.  Right now the workshop doesn't address that.
It ended up preventing the con organizers from feeling comfortable putting the signup forms out in the public.

**Comment by dpcybuck** [comment]
Note: Karl mentioned that this isn't necessarily a problem for Derby.  Workshops are out side of the talks area.  Not that the workshop should take people off the street.  But there is no problem of a resume workshop attendee getting into the conference.

**Comment by dpcybuck** [comment]
After seeing how this works in Derby2018, the best choice is to host the workshop behind the "gate" of the conference and restrict participation to conference attendees.  
This issue should be closed and the question of should workshop attendees have a con badge can be addressed case by case.
