### ISSUE TITLE
USB- As an attendie I would like information I can take with me to learn more.

### ISSUE THREAD

**Issue by dpcybuck** [mzbat/mirr#9]
Package up some documents, PDF, links, tools, videos, podcast recordings or whatever makes sense and put it on a USB.  Create a folder here with the content.

The USB could be used if recording the mock interview was a thing.
The USB could be branded by a sponsor, generating some funds for the workshop.

**Comment by mzbat** [comment]
I include a USB stick with tech & core interview questions and information on imposter syndrome in attendee survival kits. Here is the complete inventory list for survival kits:

yellow lanyards (hunting for job)
green lanyards (hiring)
hair bands
nail clippers
nail files
dove unisex deodorant
dove men's deodorant
pens
usb thumb drives w/ content
advil packs
tissue packs
disposable toothbrush
misc. combs
hair picks
chapstick
small altoids tin
hello my name is tags
pencil pouches
notebooks
